language: en
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: FallbackPolicy
- name: MappingPolicy
- name: FormPolicy
pipeline: 
#- name: supervised_embeddings
- name: WhitespaceTokenizer
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
  token_pattern: (?u)\b\w+\b
- name: EmbeddingIntentClassifier
#- name: DucklingHTTPExtractor
- name: "ner_duckling_http"
  url: http://localhost:8000
  #locale: "NL_Nothing"
  locale: “en_GB”
  timezone: "America/Montreal"
  dimensions: ["time"]
